apiVersion: v1
kind: Service
metadata:
  name: liveness-example
spec:
  selector:
    app: liveness-example
  ports:
  - port: 8091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-example
spec:
  selector:
    matchLabels:
      app: liveness-example
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: liveness-example
    spec:
      containers:
      - name: liveness-example
        image: diegochavezcarro/liveness-example:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 400Mi
            cpu: 400m
        ports:
        - containerPort: 8091
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1